version: 2
jobs:

  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Build bundles
      - run: yarn build

      # Use --transformIgnorePatterns to supress SyntaxError "Jest encountered an unexpected token"
      #   Details:
      #   /home/circleci/repo/node_modules/@material-ui/core/es/styles/MuiThemeProvider.js:1
      #   ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import _extends from "@babel/runtime/helpers/extends";
      #                                                                                                 ^^^^^^
      #   SyntaxError: Unexpected token import

      #      5 | import TextField from '@material-ui/core/TextField';
      #      6 | import JobGrid from "./JobGrid";
      #   >  7 | import MuiThemeProvider from "@material-ui/core/es/styles/MuiThemeProvider";
      - run: yarn test -- --transformIgnorePatterns '<rootDir>/node_modules/(?!@material-ui)'

      - persist_to_workspace:
          root: ~/repo
          paths:
            - package.json
            - node_modules/*
            - src/*
            - public/*
            - build/*
            - .git
          # Persist both source and artifacts, as the predeploy script
          # is automatically triggered

  deploy:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - attach_workspace:
            at: ~/repo
      - add_ssh_keys:
          fingerprints:
            - "71:6b:d2:01:f9:6c:19:1d:24:32:f3:7b:71:5f:67:7a"
      # Add Github's host key, or else the deploy step will hang
      - run: echo $GITHUB_SSH_HOST_KEY >> ~/.ssh/known_hosts
      - run: git config user.email $GITHUB_PUBLIC_EMAIL
      - run: git config user.name $GITHUB_PUBLIC_NAME
      - run: yarn deploy -- --repo $CIRCLE_REPOSITORY_URL

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
